services:
  postgres:
    container_name: quickylist
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRESQL_DATABASE: ${DATABASE}
      POSTGRESQL_USER: ${POSTGRESQL_USER}
      POSTGRESQL_PASSWORD: ${PASSWORD}
      POSTGRESQL_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRESQL_TIMEZONE: ${TIMEZONE}
      POSTGRESQL_LOG_TIMEZONE: ${TIMEZONE}
    volumes:
      - ./database/pg:/bitnami/postgresql
